// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutComponent: typeof import('./src/components/AboutComponent.vue')['default']
    ContactComponent: typeof import('./src/components/ContactComponent.vue')['default']
    FeaturesComponent: typeof import('./src/components/FeaturesComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HomeComponent: typeof import('./src/components/HomeComponent.vue')['default']
    IBxlXing: typeof import('~icons/bxl/xing')['default']
    IIonLogoSass: typeof import('~icons/ion/logo-sass')['default']
    IMdiBootstrap: typeof import('~icons/mdi/bootstrap')['default']
    IMdiLanguageCsharp: typeof import('~icons/mdi/language-csharp')['default']
    IMdiLanguageCss3: typeof import('~icons/mdi/language-css3')['default']
    IMdiLanguageHtml5: typeof import('~icons/mdi/language-html5')['default']
    IMdiLanguageJava: typeof import('~icons/mdi/language-java')['default']
    IMdiLanguageJavascript: typeof import('~icons/mdi/language-javascript')['default']
    IMdiLanguageTypescript: typeof import('~icons/mdi/language-typescript')['default']
    IMdiMicrosoftVisualStudio: typeof import('~icons/mdi/microsoft-visual-studio')['default']
    IMdiMicrosoftVisualStudioCode: typeof import('~icons/mdi/microsoft-visual-studio-code')['default']
    IMdiVuejs: typeof import('~icons/mdi/vuejs')['default']
    IMdiVuetify: typeof import('~icons/mdi/vuetify')['default']
    ISimpleIconsBitbucket: typeof import('~icons/simple-icons/bitbucket')['default']
    ISimpleIconsConfluence: typeof import('~icons/simple-icons/confluence')['default']
    ISimpleIconsDocker: typeof import('~icons/simple-icons/docker')['default']
    ISimpleIconsIntellijidea: typeof import('~icons/simple-icons/intellijidea')['default']
    ISimpleIconsJenkins: typeof import('~icons/simple-icons/jenkins')['default']
    ISimpleIconsJirasoftware: typeof import('~icons/simple-icons/jirasoftware')['default']
    ISimpleIconsMicrosoftsqlserver: typeof import('~icons/simple-icons/microsoftsqlserver')['default']
    ISimpleIconsMysql: typeof import('~icons/simple-icons/mysql')['default']
    ISimpleIconsPostgresql: typeof import('~icons/simple-icons/postgresql')['default']
    ISimpleIconsResharper: typeof import('~icons/simple-icons/resharper')['default']
    ISimpleIconsRider: typeof import('~icons/simple-icons/rider')['default']
    ISimpleIconsSpring: typeof import('~icons/simple-icons/spring')['default']
    ISimpleIconsSpringboot: typeof import('~icons/simple-icons/springboot')['default']
    ISimpleIconsTeamcity: typeof import('~icons/simple-icons/teamcity')['default']
    IUilBrain: typeof import('~icons/uil/brain')['default']
    IUilGithub: typeof import('~icons/uil/github')['default']
    IUilGitlab: typeof import('~icons/uil/gitlab')['default']
    IUilGlobe: typeof import('~icons/uil/globe')['default']
    IUilHeart: typeof import('~icons/uil/heart')['default']
    IUilUser: typeof import('~icons/uil/user')['default']
  }
}
