# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
    push:
        branches:
            - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: write
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    # Single deploy job since we're just deploying
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Update version
              run: echo "NEW_VERSION=$(npm version prerelease --no-git-tag-version)" >> $GITHUB_ENV

            - name: Commit new version
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config --global user.email "16022563+jakobsautter@users.noreply.github.com "
                git config --global user.name "GitHub Actions"
                git add "package.json"
                git add "package-lock.json"
                git commit -m "chore: release ${{ env.NEW_VERSION }}"
                git push

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: npm-${{ hashFiles('package-lock.json') }}
                  restore-keys: npm-

            - name: Install dependencies
              run: npm ci --ignore-scripts

            - name: Build
              run: npm run build

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  # Upload entire repository
                  path: './dist'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
